reporter: "xcode"

included:
  - ../Sources/

disabled_rules:
  - cyclomatic_complexity
  - identifier_name
  - line_length
  - nesting
  - unused_optional_binding

# Specialized Rules
file_length:
  - 500
