reporter: "xcode"

included:
  - ../Sources/

disabled_rules:
  - cyclomatic_complexity
  - nesting
  - unused_optional_binding
  - variable_name

# Specialized Rules
file_length:
  - 1000

line_length:
  - 200
